#!/bin/bash
# Cacheout Distribution Bundle Script
# Builds, signs, creates DMG, and notarizes for direct distribution
#
# Usage:
#   ./scripts/bundle.sh              Build unsigned .app (testing)
#   ./scripts/bundle.sh --direct     Build signed DMG for distribution (no notarization)
#   ./scripts/bundle.sh --notarize   Full pipeline: build + sign + DMG + notarize
#   ./scripts/bundle.sh --release    Alias for --notarize

set -e
set -o pipefail

APP_NAME="Cacheout"
BUNDLE_ID="com.cacheout.app"
VERSION=$(cat VERSION 2>/dev/null || echo "1.0.0")
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="$PROJECT_DIR/.build/release"
DEST_DIR="$PROJECT_DIR/build"
APP_BUNDLE="$APP_NAME.app"

echo ""
echo "📦 Cacheout Distribution Builder v${VERSION}"
echo "=========================================="
echo ""

# Detect certificates
echo "🔍 Detecting certificates..."
DEVID_CERT=$(security find-identity -v -p codesigning | grep -E "Developer ID Application" | head -1 | sed 's/.*"\(.*\)".*/\1/' || true)
echo "  Developer ID Application: ${DEVID_CERT:-❌ Not found}"
echo ""

# Build release binary
build_release() {
    echo "🏗️  Building release binary (universal)..."
    cd "$PROJECT_DIR"
    swift build -c release 2>&1

    if [ ! -f "$BUILD_DIR/$APP_NAME" ]; then
        echo "❌ Build failed - executable not found"
        exit 1
    fi
    if [ ! -f "$BUILD_DIR/CacheoutHelper" ]; then
        echo "❌ Build failed - CacheoutHelper executable not found at $BUILD_DIR/CacheoutHelper"
        exit 1
    fi

    echo "✅ Build complete"
}

# Create .app bundle
create_bundle() {
    local SIGN_CERT="$1"
    
    echo "📁 Creating app bundle..."
    mkdir -p "$DEST_DIR"
    rm -rf "$DEST_DIR/$APP_BUNDLE"
    mkdir -p "$DEST_DIR/$APP_BUNDLE/Contents/MacOS"
    mkdir -p "$DEST_DIR/$APP_BUNDLE/Contents/Resources"
    mkdir -p "$DEST_DIR/$APP_BUNDLE/Contents/Frameworks"

    # Copy executable
    cp "$BUILD_DIR/$APP_NAME" "$DEST_DIR/$APP_BUNDLE/Contents/MacOS/$APP_NAME"

    # Bundle Sparkle.framework (linked by SPM) into Contents/Frameworks
    if [ -d "$BUILD_DIR/Sparkle.framework" ]; then
        ditto "$BUILD_DIR/Sparkle.framework" "$DEST_DIR/$APP_BUNDLE/Contents/Frameworks/Sparkle.framework"
        echo "   ✓ Sparkle.framework bundled"
    else
        echo "❌ Sparkle.framework not found in $BUILD_DIR"
        exit 1
    fi

    # The SPM-built binary has @loader_path rpath but no @executable_path/../Frameworks.
    # Add the standard Frameworks rpath so dyld finds @rpath/Sparkle.framework at runtime.
    if ! otool -l "$DEST_DIR/$APP_BUNDLE/Contents/MacOS/$APP_NAME" \
        | grep -A2 LC_RPATH | grep -q "@executable_path/../Frameworks"; then
        install_name_tool -add_rpath "@executable_path/../Frameworks" \
            "$DEST_DIR/$APP_BUNDLE/Contents/MacOS/$APP_NAME"
        echo "   ✓ Added @executable_path/../Frameworks rpath"
    fi

    # Copy icon
    if [ -f "$PROJECT_DIR/Cacheout.icns" ]; then
        cp "$PROJECT_DIR/Cacheout.icns" "$DEST_DIR/$APP_BUNDLE/Contents/Resources/Cacheout.icns"
        echo "   ✓ Icon embedded"
    fi

    # Copy menubar icon resources. Bundle.main.image(forResource:) at
    # CacheoutApp.swift expects these directly in Contents/Resources/ — the
    # SPM-managed Cacheout_Cacheout.bundle is not searched.
    #
    # We ship TIFFs (1x+2x merged into a single multi-rep file via tiffutil)
    # instead of loose @1x/@2x PNG pairs. Loose PNG pairs load via
    # Bundle.main.image() but the resulting NSImage doesn't preserve the
    # template flag for NSStatusItem.button — so on a dark/translucent menubar
    # the icon stays black instead of being tinted white by AppKit.
    # Multi-rep TIFFs produce a proper template-respecting NSImage (this is
    # the same format Xcode's actool used to emit for the working v2.0.0
    # build). The TIFFs are generated by:
    #   tiffutil -cathidpicheck MenuBarIcon.png MenuBarIcon@2x.png \
    #            -out MenuBarIcon.tiff
    local MENUBAR_RES_SRC="$PROJECT_DIR/Sources/Cacheout/Resources"
    for tiff in MenuBarIcon.tiff MenuBarIconTemplate.tiff; do
        if [ -f "$MENUBAR_RES_SRC/$tiff" ]; then
            cp "$MENUBAR_RES_SRC/$tiff" "$DEST_DIR/$APP_BUNDLE/Contents/Resources/$tiff"
        else
            echo "⚠️  $tiff missing — regenerate with:"
            echo "    tiffutil -cathidpicheck ${tiff%.tiff}.png ${tiff%.tiff}@2x.png -out $tiff"
        fi
    done
    echo "   ✓ Menubar icon TIFFs embedded"

    # Bundle the privileged helper daemon at Contents/Library/LaunchDaemons/.
    # SMAppService.daemon(plistName:) registers from this path, so without it
    # the install-helper onboarding flow fails silently and autopilot is
    # unavailable in --daemon mode.
    local HELPER_BIN="$BUILD_DIR/CacheoutHelper"
    local HELPER_PLIST="$MENUBAR_RES_SRC/com.cacheout.memhelper.plist"
    if [ -f "$HELPER_BIN" ] && [ -f "$HELPER_PLIST" ]; then
        mkdir -p "$DEST_DIR/$APP_BUNDLE/Contents/Library/LaunchDaemons"
        cp "$HELPER_BIN" "$DEST_DIR/$APP_BUNDLE/Contents/Library/LaunchDaemons/CacheoutHelper"
        cp "$HELPER_PLIST" "$DEST_DIR/$APP_BUNDLE/Contents/Library/LaunchDaemons/com.cacheout.memhelper.plist"
        echo "   ✓ CacheoutHelper daemon + plist bundled"
    else
        echo "⚠️  CacheoutHelper not found at $HELPER_BIN — onboarding install-helper flow will fail"
    fi

    # Create Info.plist
    cat > "$DEST_DIR/$APP_BUNDLE/Contents/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleExecutable</key>
    <string>${APP_NAME}</string>
    <key>CFBundleIdentifier</key>
    <string>${BUNDLE_ID}</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>${APP_NAME}</string>
    <key>CFBundleDisplayName</key>
    <string>Cacheout</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>${VERSION}</string>
    <key>CFBundleVersion</key>
    <string>${VERSION}</string>
    <key>LSMinimumSystemVersion</key>
    <string>14.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>LSApplicationCategoryType</key>
    <string>public.app-category.utilities</string>
    <key>CFBundleIconFile</key>
    <string>Cacheout</string>
    <key>LSUIElement</key>
    <false/>
    <key>NSHumanReadableCopyright</key>
    <string>Copyright © 2025 This Local, Inc. MIT License.</string>
    <!-- TCC usage strings (R9). Key set mirrors
         ProjectTreeWalker.tccProtectedAncestorNames — keep the three locations
         in sync: this heredoc, Sources/Cacheout/Info.plist, and the
         INFOPLIST_KEY_* entries in project.yml. Downloads is defensive:
         no current scan walks ~/Downloads, but the key ships so any future
         Downloads-reaching scanner prompts with an explanation. -->
    <key>NSDocumentsFolderUsageDescription</key>
    <string>Cacheout looks for developer build-artifact folders (target/, node_modules/, .venv/ and similar) and stale git worktrees in Documents during scans you start. Nothing is deleted without your confirmation.</string>
    <key>NSDesktopFolderUsageDescription</key>
    <string>Cacheout looks for developer build-artifact folders (target/, node_modules/, .venv/ and similar) and stale git worktrees on your Desktop during scans you start. Nothing is deleted without your confirmation.</string>
    <key>NSDownloadsFolderUsageDescription</key>
    <string>Cacheout reads Downloads only if a scan you start includes it, to find developer caches. Nothing is deleted without your confirmation.</string>
</dict>
</plist>
PLIST
    
    echo -n "APPL????" > "$DEST_DIR/$APP_BUNDLE/Contents/PkgInfo"
    
    # Sign — Sparkle.framework (and its inner XPC services / Updater.app) MUST be
    # signed before the outer app, with hardened runtime when using a Developer ID.
    # Per Sparkle's sandboxing docs (https://sparkle-project.org/documentation/sandboxing/),
    # Downloader.xpc must be re-signed with --preserve-metadata=entitlements (Sparkle 2.6+);
    # the other inner items do NOT use that flag.
    local SPARKLE="$DEST_DIR/$APP_BUNDLE/Contents/Frameworks/Sparkle.framework"
    if [ -n "$SIGN_CERT" ]; then
        echo "🔐 Signing Sparkle inner components with: $SIGN_CERT"
        # Downloader.xpc keeps its entitlements (network / sandbox in some Sparkle builds)
        if [ -e "$SPARKLE/Versions/B/XPCServices/Downloader.xpc" ]; then
            codesign --force --options runtime \
                --preserve-metadata=entitlements \
                --sign "$SIGN_CERT" \
                "$SPARKLE/Versions/B/XPCServices/Downloader.xpc"
        fi
        # Other inner items: standard re-sign, no entitlements to preserve
        for inner in \
            "$SPARKLE/Versions/B/XPCServices/Installer.xpc" \
            "$SPARKLE/Versions/B/Updater.app" \
            "$SPARKLE/Versions/B/Autoupdate"; do
            if [ -e "$inner" ]; then
                codesign --force --options runtime --sign "$SIGN_CERT" "$inner"
            fi
        done
        codesign --force --options runtime --sign "$SIGN_CERT" "$SPARKLE"

        # Sign the privileged helper before the outer app — codesign --verify
        # walks the bundle and will fail if any nested Mach-O isn't signed.
        local HELPER="$DEST_DIR/$APP_BUNDLE/Contents/Library/LaunchDaemons/CacheoutHelper"
        if [ -e "$HELPER" ]; then
            echo "🔐 Signing CacheoutHelper..."
            codesign --force --options runtime --sign "$SIGN_CERT" "$HELPER"
        fi

        echo "🔐 Signing app with: $SIGN_CERT"
        codesign --force --options runtime \
            --sign "$SIGN_CERT" \
            "$DEST_DIR/$APP_BUNDLE"

        echo "🔍 Verifying signature..."
        codesign --verify --deep --strict --verbose=2 "$DEST_DIR/$APP_BUNDLE"
    else
        echo "🔓 Ad-hoc signing (no certificate)..."
        codesign --force --deep --sign - "$DEST_DIR/$APP_BUNDLE"
    fi
    
    BUNDLE_SIZE=$(du -sh "$DEST_DIR/$APP_BUNDLE" | cut -f1)
    echo "✅ Bundle ready: $DEST_DIR/$APP_BUNDLE ($BUNDLE_SIZE)"
}

# Create polished DMG
create_dmg() {
    echo ""
    echo "💿 Creating polished DMG..."
    DMG_NAME="${APP_NAME}-${VERSION}.dmg"
    DMG_PATH="$DEST_DIR/$DMG_NAME"
    rm -f "$DMG_PATH"
    
    if command -v create-dmg &> /dev/null; then
        create-dmg \
            --volname "$APP_NAME" \
            --volicon "$PROJECT_DIR/Cacheout.icns" \
            --background "$PROJECT_DIR/Resources/DMG/background.png" \
            --window-pos 200 120 \
            --window-size 660 400 \
            --icon-size 128 \
            --icon "$APP_BUNDLE" 165 190 \
            --hide-extension "$APP_BUNDLE" \
            --app-drop-link 495 190 \
            --no-internet-enable \
            "$DMG_PATH" \
            "$DEST_DIR/$APP_BUNDLE" || true
            # create-dmg returns non-zero even on success sometimes
    else
        echo "⚠️  create-dmg not found, falling back to basic DMG"
        echo "   Install with: brew install create-dmg"
        DMG_TEMP="$DEST_DIR/dmg_temp"
        rm -rf "$DMG_TEMP"
        mkdir -p "$DMG_TEMP"
        cp -R "$DEST_DIR/$APP_BUNDLE" "$DMG_TEMP/"
        ln -s /Applications "$DMG_TEMP/Applications"
        hdiutil create -volname "$APP_NAME" -srcfolder "$DMG_TEMP" -ov -format UDZO "$DMG_PATH"
        rm -rf "$DMG_TEMP"
    fi
    
    # Sign DMG
    if [ -n "$DEVID_CERT" ]; then
        echo "🔐 Signing DMG..."
        codesign --force --sign "$DEVID_CERT" "$DMG_PATH"
    fi
    
    if [ -f "$DMG_PATH" ]; then
        DMG_SIZE=$(du -sh "$DMG_PATH" | cut -f1)
        echo "✅ DMG created: $DMG_PATH ($DMG_SIZE)"
    else
        echo "❌ DMG creation failed"
        exit 1
    fi
}

# Notarize DMG
notarize_dmg() {
    DMG_PATH="$DEST_DIR/${APP_NAME}-${VERSION}.dmg"
    
    if [ ! -f "$DMG_PATH" ]; then
        echo "❌ DMG not found: $DMG_PATH"
        echo "   Run './scripts/bundle.sh --direct' first"
        return 1
    fi
    
    echo ""
    echo "📤 Submitting for notarization..."
    echo "   (This may take a few minutes)"
    
    # Check for stored credentials
    if ! xcrun notarytool history --keychain-profile "notarytool-profile" &>/dev/null; then
        echo ""
        echo "⚠️  No stored credentials found!"
        echo "   First, store your credentials:"
        echo "   xcrun notarytool store-credentials notarytool-profile \\"
        echo "     --apple-id YOUR_APPLE_ID \\"
        echo "     --team-id YOUR_TEAM_ID \\"
        echo "     --password APP_SPECIFIC_PASSWORD"
        echo ""
        echo "   Generate an app-specific password at: https://appleid.apple.com"
        return 1
    fi
    
    xcrun notarytool submit "$DMG_PATH" \
        --keychain-profile "notarytool-profile" \
        --wait
    
    echo "📎 Stapling notarization ticket..."
    xcrun stapler staple "$DMG_PATH"
    
    echo "✅ Notarization complete! DMG is ready for distribution."
}

# RELEASE-BLOCKING cross-repo gates (fn-5.6)
#
# Some release preconditions live in ANOTHER repository — a coordinated
# consumer that must adopt a contract before this build ships. Nothing in
# this repo's own test suite can observe that, so the gate is RECORDED in
# CHANGELOG.md's [Unreleased] section (named consumer, owner, verification,
# and ONE status line) and enforced HERE, on every DISTRIBUTION-producing
# mode. Merging with an open gate is fine and deliberate; shipping an
# artifact with one is not — and `--direct` produces a signed, distributable
# DMG just as `--release` does, so both arms run this. The default no-flag
# mode builds an unsigned .app for local testing and produces no
# distributable artifact, so it deliberately does not.
#
# RECORDED FORM, and it is CHECKED — not merely searched for. Each gate is a
# `**RELEASE-BLOCKING` marker in [Unreleased] paired with exactly ONE status
# line, and a status line has exactly two admissible forms:
#
#     Status: **NOT SATISFIED**            → blocks
#     Status: **SATISFIED at <hex7-40>**   → passes
#
# EVERYTHING ELSE BLOCKS — a missing [Unreleased] section, a gate whose
# status line was deleted, a duplicate or orphan status line, a typo, or
# `Status: **SATISFIED**` with no commit to check. Searching only for the
# open marker would FAIL OPEN on every one of those: deleting the status
# line would "close" the gate. Enumerating the admissible states instead
# means only a provably-satisfied gate lets a distribution build run.
#
# Keying on the status LINE (not on any occurrence of the phrase) is what
# lets the paragraphs above explain the mechanism — and lets a future entry
# quote it — without blocking every release.
check_release_gates() {
    changelog="$PROJECT_DIR/CHANGELOG.md"
    if [ ! -f "$changelog" ]; then
        echo "❌ CHANGELOG.md not found — release gates cannot be verified"
        return 1
    fi
    if ! grep -qE '^## \[Unreleased\]' "$changelog"; then
        echo "❌ CHANGELOG.md has no [Unreleased] section — release gates cannot be verified"
        return 1
    fi
    # The [Unreleased] section only: gates in shipped sections are history,
    # not preconditions.
    unreleased=$(awk '/^## \[Unreleased\]/{inside=1; next} /^## \[/{inside=0} inside' "$changelog")

    # (a) STRUCTURE — each gate marker is followed by exactly one status line
    # before the next marker. Counting markers against statuses is NOT
    # equivalent: two gates where one carries two statuses and the other none
    # would balance out, leaving an unverified gate. Positional pairing is
    # what the recorded form actually claims, so that is what is checked.
    #
    # A STATUS LINE IS ANY `Status:` LINE, well-formed or not. Recognizing
    # only the well-formed spelling here would let a typo'd line
    # (`Status: *NOT SATISFIED*`) be skipped as prose, so a valid status
    # beneath it would close a gate the typo was trying to hold open.
    # Structure first over every candidate, spelling second — a malformed
    # status is then either an ORPHAN (two under one gate) or refused by
    # name in pass (b).
    pairing=$(printf '%s\n' "$unreleased" | awk '
        /\*\*RELEASE-BLOCKING/ {
            if (awaiting) { print "MISSING_STATUS"; exit }
            awaiting = 1; gates++; next
        }
        /^[ \t]*Status:/ {
            if (!awaiting) { print "ORPHAN_STATUS\t" $0; exit }
            awaiting = 0; next
        }
        END { if (awaiting) print "MISSING_STATUS"; else print "OK\t" gates+0 }
    ')
    case "$pairing" in
        MISSING_STATUS*)
            echo "❌ CHANGELOG.md [Unreleased]: a RELEASE-BLOCKING gate has no status line."
            echo "   Every gate carries EXACTLY ONE 'Status: **…**' line beneath it."
            echo "   An unverifiable gate never passes."
            return 1
            ;;
        ORPHAN_STATUS*)
            echo "❌ CHANGELOG.md [Unreleased]: a gate status line belongs to no gate:"
            echo "  ${pairing#ORPHAN_STATUS	}"
            echo "   A duplicate or stray status means the record is broken, so the"
            echo "   gate it claims to describe cannot be verified."
            return 1
            ;;
    esac

    gate_count=${pairing#OK	}
    if [ "$gate_count" = "0" ]; then
        echo "✅ No release-blocking gates recorded in CHANGELOG.md [Unreleased]"
        return 0
    fi

    # (b) SPELLING — every paired status is one of the two admissible forms.
    status_lines=$(printf '%s\n' "$unreleased" | grep -E '^[[:space:]]*Status:' || true)

    # Enumerate the admissible states; anything else is refused by name.
    while IFS= read -r line; do
        case "$line" in
            *[![:space:]]*) ;;
            *) continue ;;
        esac
        case "$line" in
            *"Status: **NOT SATISFIED**"*)
                echo "❌ An open release-blocking gate in CHANGELOG.md [Unreleased]:"
                echo "  $line"
                echo "   Run the gate's recorded verification, then replace that line's"
                echo "   **NOT SATISFIED** with **SATISFIED at <commit-hash>**."
                return 1
                ;;
        esac
        if ! printf '%s\n' "$line" |
             grep -qE '^[[:space:]]*Status: \*\*SATISFIED at [0-9a-f]{7,40}\*\*'; then
            echo "❌ Malformed release-gate status in CHANGELOG.md [Unreleased]:"
            echo "  $line"
            echo "   Admissible: 'Status: **NOT SATISFIED**' or"
            echo "   'Status: **SATISFIED at <commit-hash>**' (7-40 hex characters)."
            echo "   Anything else is unverifiable and therefore blocks."
            return 1
        fi
    done <<STATUS_LINES
$status_lines
STATUS_LINES

    echo "✅ Every release-blocking gate in CHANGELOG.md [Unreleased] is satisfied"
}

# Main
case "${1:-}" in
    --direct)
        # A signed, distributable DMG — the same shipping artifact the
        # release arm produces, minus notarization. Gated identically.
        check_release_gates
        if [ -z "$DEVID_CERT" ]; then
            echo "❌ Developer ID Application certificate required!"
            echo "   Found in Keychain? Check: security find-identity -v -p codesigning"
            exit 1
        fi
        build_release
        create_bundle "$DEVID_CERT"
        create_dmg
        echo ""
        echo "🚀 Direct distribution build complete!"
        echo ""
        echo "To notarize (required for Gatekeeper):"
        echo "  ./scripts/bundle.sh --notarize"
        ;;

    --notarize|--release)
        # --notarize now performs the full pipeline (build + sign + DMG + notarize).
        # --release is kept as an alias for the same operation.
        #
        # Release gates FIRST: an open cross-repo gate must stop the pipeline
        # before it builds, signs, or submits anything for notarization.
        check_release_gates
        if [ -z "$DEVID_CERT" ]; then
            echo "❌ Developer ID Application certificate required!"
            echo "   Found in Keychain? Check: security find-identity -v -p codesigning"
            exit 1
        fi
        build_release
        create_bundle "$DEVID_CERT"
        create_dmg
        notarize_dmg
        echo ""
        echo "🎉 Full release pipeline complete!"
        echo "   DMG: $DEST_DIR/${APP_NAME}-${VERSION}.dmg"
        ;;
    
    *)
        build_release
        create_bundle ""
        echo ""
        echo "=========================================="
        echo "🎉 Test build complete!"
        echo ""
        echo "🚀 To run:  open $DEST_DIR/$APP_BUNDLE"
        echo ""
        echo "Distribution options:"
        echo "  ./scripts/bundle.sh --direct    Build signed DMG (no notarization)"
        echo "  ./scripts/bundle.sh --notarize  Full pipeline: build + sign + DMG + notarize"
        echo "  ./scripts/bundle.sh --release   Alias for --notarize"
        ;;
esac
